<?php

declare(strict_types=1);

namespace ProtonLabs\AdblockParser;

class RuleAggregateSaver
{
    public function save(RuleAggregate $ruleAggregate, string $savedFilePath): bool
    {
        $export = var_export($ruleAggregate->toArray(), return: true);
        $selfFqcn = self::class;
        $out = <<<OUT
            <?php
            // This file has been auto-generated by $selfFqcn

            return $export;

            OUT;

        $success = file_put_contents($savedFilePath, $out);

        return (bool) $success;
    }

    public function load(string $savedFilePath): ?RuleAggregate
    {
        if (!file_exists($savedFilePath)) {
            return null;
        }

        $export = include $savedFilePath;

        $ruleAggregate = RuleAggregate::fromArray($export);
        assert($ruleAggregate instanceof RuleAggregate);

        return $ruleAggregate;
    }
}
